#!/bin/bash

#this is a comment

#creates a ls cmd to execute:
#ls

#prints the following sentence:
echo "\"i'm writing this and you're reading it\""

#creates a 2 directories Albert and Thierry
#Thierry has 2 sub directories Travail et Photos
#Albert has 2 directories Compta and Images

#mkdir Exercices
#cd Exercices

#mkdir Albert Thierry

#cd Albert/ 

#mkdir Compta Images

#cd ../Thierry

#mkdir Travail Photos

#cd ../

#mkdir Albert/Compta/2011 Albert/Compta/2012 Albert/Compta/2013 Albert/Compta/2014

#touch Albert/Compta/2011/2011 Albert/Compta/2012/2012 Albert/Compta/2013/2013 Albert/Compta/2014/2014

#mkdir Thierry/Travail/Client1 Thierry/Travail/Client2 Thierry/Travail/Client3

#touch Thierry/Travail/Client1/CL1.txt Thierry/Travail/Client2/CL2.txt Thierry/Travail/Client3/CL3.txt
 

#displays the following message:
#echo "Hi, what\'s your name?"
#waits for the user's answer:
#read
#now display the user's answer:
#echo "Hi, there $REPLY"
#creates a variable called name containing the value of the reply at that time
#name=$REPLY
#echo "How old are you?"
#read
#age=$REPLY
#echo "So you're $REPLY, right?"
#echo "OK, well hello $name, i'm glad you're $age years old"
#if [ $age -ge 18 ]
#then
#	echo "you're legal"
#else

#	echo "you're not legal"
#fi 

: '
# while loop:
i=0
while [ $i -le 5 ]
do 
	echo "i = $i"
i=$(( $i + 1 ))
done
'


#break an infinite loop
# i=1
# while [ $i -eq 1 ]
# do
# 	echo "repeat"
# 	break
# done



